// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALAwK_iosJWnVYRk7ArCbGV257okBcEg',
    appId: '1:296165423529:web:739118901cfe0ede872cb8',
    messagingSenderId: '296165423529',
    projectId: 'travel-in-a-box',
    authDomain: 'travel-in-a-box.firebaseapp.com',
    storageBucket: 'travel-in-a-box.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUYZ_hgnTOEyqR-ruUIYO2lAPL3hMIXo',
    appId: '1:296165423529:android:d617b8496bd395f5872cb8',
    messagingSenderId: '296165423529',
    projectId: 'travel-in-a-box',
    storageBucket: 'travel-in-a-box.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtMF3tSmGFiPLp8IPTicC52EvIOKxKXLc',
    appId: '1:296165423529:ios:33481e410a6ce344872cb8',
    messagingSenderId: '296165423529',
    projectId: 'travel-in-a-box',
    storageBucket: 'travel-in-a-box.firebasestorage.app',
    iosBundleId: 'com.example.travelInABox',
  );

}